### ISSUE TITLE
Yarn `clean-build` Error: File not found with singular glob | Failure to launch dev server

### ISSUE THREAD

**Issue by tcbutler320** [netlify/templates#135]
**Bug Report**

**Issue**.   
Yarn fails to start development server with error on `clean-build`

**Steps to Reproduce**

1. Fork the repository 

2. Clone the fork
```git clone https://github.com/tcbutler320/templates.git ```
3. CD into folder
```cd templates```
4. Run yarn to install dependancies   

```bash
➜  templates git:(master) yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 5.00s.
```    
5. Run yarn start to launch dev server.   

```bash
➜  templates git:(master) yarn start
yarn run v1.22.10
$ gulp build:local && gulp serve & gulp watch
[19:38:33] [19:38:33] Using gulpfile ~/Documents/projects/programming/Github/templates/gulpfile.js
Using gulpfile ~/Documents/projects/programming/Github/templates/gulpfile.js
[19:38:33] [19:38:33] Starting 'watch'...
Starting 'build:local'...
[19:38:33] Starting 'clean-build'...
[19:38:33] 'clean-build' errored after 7.12 ms
[19:38:33] Error: File not found with singular glob: /Users/tylerbutler/Documents/projects/programming/Github/templates/dist (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/tylerbutler/Documents/projects/programming/Github/templates/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:428:26)
    at Glob.emit (events.js:321:20)
    at Glob.EventEmitter.emit (domain.js:482:12)
    at Glob._finish (/Users/tylerbutler/Documents/projects/programming/Github/templates/node_modules/glob/glob.js:197:8)
    at done (/Users/tylerbutler/Documents/projects/programming/Github/templates/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/tylerbutler/Documents/projects/programming/Github/templates/node_modules/glob/glob.js:688:12)
    at /Users/tylerbutler/Documents/projects/programming/Github/templates/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/tylerbutler/Documents/projects/programming/Github/templates/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/tylerbutler/Documents/projects/programming/Github/templates/node_modules/glob/glob.js:764:12)
[19:38:33] 'build:local' errored after 11 ms
```    

<img width="1524" alt="netlify-templates-issue" src="https://user-images.githubusercontent.com/41709108/98881459-10a67b00-2458-11eb-8734-a0c67cd39766.png">

**Expected Behavior**  
With dependancies installed dev server should launch with no error. I suspect this would have something to do with my own setup but I've yet to find a solution.

**System Information**  
  
Mac OSX Catalina: 10.15.7 (19H2)
- Yarn: 1.22.10    
- Node: v12.16.0
- Git: 2.23.0

**Comment by makma** [comment]
I'm facing the same issue.

- OS: Windows 10 Pro 20H2 19042.746
- yarn version: 1.22.10
- node version: v14.15.1
- git version: 2.26.2.windows.1

**Comment by benedfit** [comment]
Currently requires the `dist` directory to exist. Running `mkdir dist` as a workaround before starting locally solves this issue
